### PR TITLE
Changes to information displayed

### PR DESCRIPTION
**Pull request by shortwood**
- Added code to display ReplayTV and DVR titles when playing.
- Added an update function when changing source so update is reflected in HA.

### CODE REVIEW

**Comment by Sholofly** [comment]
Thank you @shortwood shortwood. Will test this as soon as possible.

**Comment by Sholofly** [comment]
Looks good. Thank you!

**Comment by shortwood** [comment]
Cool! I’m also (still) trying to work out how to keep the messages from the mqtt server coming even when you switch channels using the Remote. This currently only works for me when there is at least one HGO client connected (i.e. ZiggoGo.tv is opened and logged in).

**Comment by Sholofly** [comment]
Would be nice!

**Pull request merged**
